#!/bin/sh

uci set luci.main.lang=auto
uci commit luci

uci set system.@system[0].timezone='CET-1CEST,M3.5.0,M10.5.0/3'
uci set system.@system[0].zonename='Europe/Paris'
uci set system.led_wan.mode='link'
uci set system.led_lan.mode='link'
uci commit system

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

exit 0
